#!/bin/bash
set -e

apt-get -y update
apt-get -y dist-upgrade
apt-get -y install git wget letsencrypt

wget http://nginx.org/keys/nginx_signing.key
apt-key add nginx_signing.key
echo "deb http://nginx.org/packages/mainline/ubuntu/ xenial nginx" > /etc/apt/sources.list.d/nginx.list
apt-get -y update
apt-get -y install nginx

curl https://get.docker.com | sh
